parameters:
#    vizitka.example.class: Vizitka\SiteBundle\Example

services:
#    vizitka.example:
#        class: %vizitka.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
